version: "3.8"

services:
  tor:
    build: tor
    read_only: true
    tmpfs:
      - /var/lib/tor:size=16M,uid=100,gid=100
    networks:
      - nginx-network
      - internet
  nginx:
    image: nginx:1.23.2
    read_only: true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./serve:/usr/share/nginx/html
    tmpfs:
      - /run:size=1M
      - /var/cache/nginx:size=1M
    networks:
      - nginx-network
    deploy:
      resources:
        limits:
          memory: 100M

networks:
  nginx-network:
    internal: true
  internet:
